### ISSUE TITLE
Spring Clean-up!

### ISSUE THREAD

**Issue by Nirmal4G** [onovotny/MSBuildSdkExtras#56]
#### 1. Build + DefaultItems Support:
- [ ] WFF (Closes #59)
- [ ] ASP.NET/WCF (Closes #60)
- [x] WinForms/WPF (Closes #66)
- [ ] UWP (Closes #67)
- [x] .NET CF (Closes #48)
- [x] Portable Library 5.0

Some Designer features work, the ones implemented with CPS

#### 2. SDK state:
- [x] Package and SDK-style (Closes #64)
- [x] Clean separation of Application and Library/Console support for all .NET platforms

**Comment by Nirmal4G** [comment]
I have preliminary bits in my repo, I'm currently testing now. So Far So Good!

But the problem is Mine diverges a lot from current state of Extras SDK mostly with property renames, default items, with a pinch of behavioural changes. I have already tested with my projects and default templates. It works surprisingly well! No major issues so far even the ones tracked here!!

With that said It's not ripe for PR yet and so I need some help in testing this in real projects. There are some renames consistent with the main SDK and Common targets.

I'll comment here with Package and ReadMe link sometime tomorrow morning!

**Comment by Nirmal4G** [comment]
As promised, here's the myget gallery link:

#### MSBuild.NET.Extras.Sdk:

[![MSBuild.NET.Extras.Sdk](https://img.shields.io/myget/msbuild-sdks/v/MSBuild.NET.Extras.Sdk.svg)](https://myget.org/feed/msbuild-sdks/package/nuget/MSBuild.NET.Extras.Sdk)

**Comment by Nirmal4G** [comment]
Please test the SDK and give feedback, so that I can merge those features into this project!

If you find any issues, report it, within this thread or create a issue on [my repo](https://github.com/nirin/msbuild-sdks/issues)

**Comment by Nirmal4G** [comment]
@onovotny props/targets code updates are ready. But there are large changes. I tried rebasing the patches from my project but it doesn't work, since my old snapshot of your changes (#23) has diverged a lot.

**Comment by onovotny** [comment]
Can you please break it up into a series of PR's? Each can be focused on a set of changes/improvements. It's much easier to review that way and also helps provide a clean commit history showing what was done.

**Comment by Nirmal4G** [comment]
Ok, will do, but the changes are dependent on each other, to break them into separate PR each instead of creating commits seems like a lot of unnecessary work.

Can you do a merge commit instead of squash, so that I can break it into separate logical commits within the same PR?

**Comment by onovotny** [comment]
I can do that
